fix(editor): fix ClientErrorMessage by using `$i18n` in template
The snapshot test should be good enough as there is basically no logic
involved in this component. The main thing that this test asserts is
that no error message is being called with something like:
"TypeError: _ctx.i18n is not a function"

Change-Id: I453ec68faa3ab72ba83c7c204738d60d10092087